### ISSUE TITLE
请问可以分享赛题数据吗？

### ISSUE THREAD

**Issue by dst111dst** [orion-orion/TipDMCup#2]
请问原始数据可以分享一下吗？

**Comment by lonelyprince7** [comment]
链接: https://pan.baidu.com/s/1-Tf-PvdMIF7dCHgsTDiaGQ&nbsp; 密码: 6tov
可以看下这个能不能用。话说同学你也是做机器学习的吗，HaHa


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lonelyprince7/TipDMCup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月22日(星期天) 凌晨0:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lonelyprince7/TipDMCup] 请问可以分享赛题数据吗？ (#2)





 
请问原始数据可以分享一下吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by orion-orion** [comment]
您好，赛题数据已上传到链接[Google drive 下载链接](https://drive.google.com/drive/folders/1ULeSHtIW-rVpqiQyEB_OONA3vUdxDAYU?usp=sharing)，欢迎下载~
