### ISSUE TITLE
同学你好，可以分享一下你们的论文吗？想对照代码学习学习。

### ISSUE THREAD

**Issue by 376498485** [orion-orion/TipDMCup#3]

**Comment by orion-orion** [comment]
可以的，不过这个论文用的模型比较简单，这是我们今年打比赛的模型https://github.com/lonelyprince7/TipDMCup21，我觉得要强大一些。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lonelyprince7/TipDMCup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月31日(星期二) 上午8:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lonelyprince7/TipDMCup] 同学你好，可以分享一下你们的论文吗？想对照代码学习学习。 (#3)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 376498485** [comment]
好的谢谢
